Update DNS
Some Bug fixes

diff --git a/dns b/dns
--- a/dns
+++ b/dns
@@ -1,82 +1,43 @@
 #!/bin/bash
+# Interactive DNS menu
 
-while true;do
-	clear
-	echo
-	echo "						DNS Resolver Setup"
-	echo "_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-"
-	echo "1)Google		2)1.1.1.1	3)Shecan	4)elctro"
-	echo 
-	echo "5)Spotify_1 	6)Spotify_2 	7)Spotify_3"
-	echo
-	echo "8)403	        9)Alternate	10)Comodo 	11)DNS.Watch	12)Level3"
-	echo
-	echo "13)OpenDNS	14)OpenNIC 	15)Quad9 	16)Verisign 	17)Yandex"
-	echo
-	echo "e) Obtain DNS server automatically"
-	echo
-	read -p "Please enter the number: " option
-	echo
-	echo "You entered: 	$option"
+SETDNS=$(command -v setdns || echo "/usr/bin/setdns")
+NODNS=$(command -v nodns || echo "/usr/bin/nodns")
 
+while true; do
+    clear
+    echo
+    echo -e "\t\t\t DNS Resolver Setup"
+    echo "-----------------------------------------------------------"
+    echo "1) Google        2) Cloudflare     3) Shecan      4) Electro"
+    echo "5) Spotify_1    6) Spotify_2      7) Spotify_3   8) 403"
+    echo "9) Alternate    10) Comodo        11) DNS.Watch  12) Level3"
+    echo "13) OpenDNS     14) OpenNIC       15) Quad9      16) Verisign"
+    echo "17) Yandex"
+    echo
+    echo "e) Revert to automatic DNS"
+    echo
+    read -p "Choose option: " option
 
-	case $option in 
-		"1") sudo /usr/bin/setdns "8.8.8.8" "8.8.4.4";
-			break;;
-
-		"2") sudo /usr/bin/setdns "1.1.1.1" "1.0.0.1";
-			break;;
-
-		"3") sudo /usr/bin/setdns "178.22.122.100" "185.51.200.2";
-			break;;
-
-		"4") sudo /usr/bin/setdns "78.157.42.100" "78.157.42.101";
-			break;;
-
-		"5") sudo /usr/bin/setdns "78.157.42.100" "1.1.1.1";
-			break;;
-	
-		"6") sudo /usr/bin/setdns "10.202.10.202" "1.1.1.1";
-			break;;
-		
-		"7") sudo /usr/bin/setdns "10.202.10.202" "185.51.200.2"
-			break;;
-		
-		"8") sudo /usr/bin/setdns "10.202.10.202" "10.202.10.102";
-			break;;
-
-		"9") sudo /usr/bin/setdns "198.101.242.72" "23.253.163.53";
-			break;;
-
-		"10") sudo /usr/bin/setdns "8.26.56.26" "8.20.247.20";
-			break;;
-				
-		"11") sudo /usr/bin/setdns "84.200.69.80" "84.200.70.40";
-			break;;
-				
-		"12") sudo /usr/bin/setdns "209.244.0.3" "209.244.0.4";
-			break;;
-					
-		"13") sudo /usr/bin/setdns "208.67.222.222" "208.67.220.220";
-			break;;
-	
-		"14") sudo /usr/bin/setdns "185.121.177.177" "169.239.202.202";
-			break;;
-	
-		"15") sudo /usr/bin/setdns "9.9.9.9" "149.112.112.112";
-			break;;
-	
-		"16") sudo /usr/bin/setdns "64.6.64.6" "64.6.65.6";
-			break;;
-	
-		"17") sudo /usr/bin/setdns "77.88.8.8" "77.88.8.1";
-			break;;
-	
-		"e") sudo /usr/bin/nodns 
-			break;;
-
-		*) clear;
-			 echo "try again"; continue;;
-
-	esac
+    case $option in
+        1) sudo "$SETDNS" "8.8.8.8" "8.8.4.4"; break;;
+        2) sudo "$SETDNS" "1.1.1.1" "1.0.0.1"; break;;
+        3) sudo "$SETDNS" "178.22.122.100" "185.51.200.2"; break;;
+        4) sudo "$SETDNS" "78.157.42.100" "78.157.42.101"; break;;
+        5) sudo "$SETDNS" "78.157.42.100" "1.1.1.1"; break;;
+        6) sudo "$SETDNS" "10.202.10.202" "1.1.1.1"; break;;
+        7) sudo "$SETDNS" "10.202.10.202" "185.51.200.2"; break;;
+        8) sudo "$SETDNS" "10.202.10.202" "10.202.10.102"; break;;
+        9) sudo "$SETDNS" "198.101.242.72" "23.253.163.53"; break;;
+        10) sudo "$SETDNS" "8.26.56.26" "8.20.247.20"; break;;
+        11) sudo "$SETDNS" "84.200.69.80" "84.200.70.40"; break;;
+        12) sudo "$SETDNS" "209.244.0.3" "209.244.0.4"; break;;
+        13) sudo "$SETDNS" "208.67.222.222" "208.67.220.220"; break;;
+        14) sudo "$SETDNS" "185.121.177.177" "169.239.202.202"; break;;
+        15) sudo "$SETDNS" "9.9.9.9" "149.112.112.112"; break;;
+        16) sudo "$SETDNS" "64.6.64.6" "64.6.65.6"; break;;
+        17) sudo "$SETDNS" "77.88.8.8" "77.88.8.1"; break;;
+        e) sudo "$NODNS"; break;;
+        *) echo "Invalid option, try again."; sleep 1;;
+    esac
 done
